# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkitos', '0002_auto_20170612_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenttag',
            old_name='created_at',
            new_name='linked_at',
        ),
    ]
